<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.testcases.nse.CheckTitle" tests="1" time="13.185" ignored="0" failures="0" timestamp="29 May 2020 11:26:24 GMT" skipped="0" hostname="LAPTOP-DNV4PNFG" errors="1">
  <testcase name="pageTitle" time="13.185" classname="com.testcases.nse.CheckTitle">
    <error type="junit.framework.ComparisonFailure" message="expected:&lt;NSE - National Stock Exchange of India Ltd.&gt; but was:&lt;Business News, Stock/Share Market Investment, Live BSE/NSE Sensex &amp; Nifty, Mutual Funds, Commodity Market, Finance Portfolio Investment/Management, Startup news India, Financial News - Moneycontrol&gt;">
      <![CDATA[junit.framework.ComparisonFailure: expected:<NSE - National Stock Exchange of India Ltd.> but was:<Business News, Stock/Share Market Investment, Live BSE/NSE Sensex & Nifty, Mutual Funds, Commodity Market, Finance Portfolio Investment/Management, Startup news India, Financial News - Moneycontrol>
	at junit.framework.Assert.assertEquals(Assert.java:81)
	at junit.framework.Assert.assertEquals(Assert.java:87)
	at com.testcases.nse.CheckTitle.pageTitle(CheckTitle.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- pageTitle -->
</testsuite> <!-- com.testcases.nse.CheckTitle -->
